### ISSUE TITLE
compilation error due to new breaking discord update

### ISSUE THREAD

**Issue by RoguedBear** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#34]
due to a recent discord update that broke most of the plugins and messed up BD as well, AutoIdleOnAFK has been affected too. 

I'll be working on a fix for it when i get some free time.

---
traceback:

```
TypeError: Cannot destructure property 'StatusSetting' of 'Webpack.getModule(...)' as it is undefined.
    at plugin (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:70:13)
    at eval (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:297:13)
    at eval (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:298:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)
```

**Comment by RoguedBear** [comment]
also use this opportunity to do the following:

- [ ] move away from update url being release asset, to a main branch url
- [ ] modify action to publish + build only on release 
- [ ] also publish sha256 hashes via actions cuz why not
- [ ] move away from build scripts to the npm build module

**Comment by Violet-Vibes** [comment]
There's an updated/forked version at https://github.com/haxurus/BetterDiscordPlugin-AutoIdleOnAFK

**Comment by Violet-Vibes** [comment]
> **UPDATE (1/10/22):** as of now, there does not appear to be a way to access the module responsible for changing the user status. Any help in this regard would be very much appreciated
> 
> due to a recent discord update that broke most of the plugins and messed up BD as well, AutoIdleOnAFK has been affected too.
> 
> The issue mainly is the module the plugin was using cannot be found now due it being changed/replaced to something else by discord. The fix would be to find the new module (again).
> 
> I'll be working on that when i get some free time.
> 
> traceback:
> 
> ```
> TypeError: Cannot destructure property 'StatusSetting' of 'Webpack.getModule(...)' as it is undefined.
>     at plugin (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:70:13)
>     at eval (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:297:13)
>     at eval (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:298:3)
>     at Object.requireAddon (<anonymous>:4:43438)
>     at Object.loadAddon (<anonymous>:4:9197)
>     at Object.loadAddon (<anonymous>:4:41165)
>     at Object.loadAllAddons (<anonymous>:4:11607)
>     at Object.initialize (<anonymous>:4:6257)
>     at Object.initialize (<anonymous>:4:40368)
>     at Object.startup (<anonymous>:4:376262)
> ```

What about using the BDFDB lib? `BDFDB.LibraryModules.SettingsUtils.StatusSetting.updateSetting`

**Comment by RoguedBear** [comment]
If the status module exposed via BDFDB works currently, then I'll have no problem using that in the plugin instead.

**Comment by RoguedBear** [comment]
I'll look into that, thanks for letting me know!

**Comment by Violet-Vibes** [comment]
> 

Thank you for making this, sadly my JS skills are subpar or I'd give it a go myself.

The specific usage is shown here, https://github.com/mwittrien/BetterDiscordAddons/blob/241da8656dc90097924407c5a63fcd54c429dca5/Plugins/CustomStatusPresets/CustomStatusPresets.plugin.js#L393

**Comment by RoguedBear** [comment]
Good news! thanks to the direction you've pointed me and looking through BDFDB's code, i have found the module used to change the status, and have successfully changed it via the console

I'll be working on a fix for the plugin now!

again, thank you @Violet-Vibes, im so happy the plugin wont have to stay dead anymore

**Comment by Violet-Vibes** [comment]
> Good news! thanks to the direction you've pointed me and looking through BDFDB's code, i have found the module used to change the status, and have successfully changed it via the console
> 
> I'll be working on a fix for the plugin now!
> 
> again, thank you @Violet-Vibes, im so happy the plugin wont have to stay dead anymore

I'm happy to hear that, thank you for fixing it.
